version: '3'

services:
  zookeeper:
    image: zookeeper:3.5.9
    restart: always
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    ports:
      - "9092:9092"
    networks:
      - kafka-network

  # backend:
  #   build: ./backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     KAFKA_HOST: kafka:9092
  #   networks:
  #     - kafka-network

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - kafka-network

networks:
  kafka-network: